### ISSUE TITLE
physical separate DCCP subflows

### ISSUE THREAD

**Issue by boucadair** [markusa/ietf-multipath-dccp#110]
The document uses this term in two occurrences. Do you mean that paths have to be completely disjoint? I'm not sure you need such restriction. sublfows may be bound to same "physical" path but still be seen as distinct subflows, IMO.

**Comment by dirkhugo** [comment]
perhaps it should be stated that the path separation mainly addresses the interface (e.g., WiFi or cellular one) at the UE - of course a complete path disjointness can seldom be guaranteed since from some aggregation node within the core on also cellular and fixed network connections may use the same (physical) fiber or copper line ... IIUIC
