### ISSUE TITLE
MP_ADDADDR for peer-initiated subflows

### ISSUE THREAD

**Issue by boucadair** [markusa/ietf-multipath-dccp#127]
The following is true: 

```
   Due to the proliferation of NATs, it is reasonably likely that one
   host may attempt to advertise private addresses. It is not desirable
   to prohibit this, since there may be cases where both hosts have
   additional interfaces on the same private network, and a host MAY
   want to advertise such addresses. 
```

The use a public address does not guarantee successful placement of incoming connections, either. Think about a host that is behind a firewall or a host that discovers the external IP address (e.g., STUN) and then advertises that address. 

I wonder whether MP_ADDADDR can include a flag (e.g., (C)onnectivty Check flag) that is set by the sender when it is safe to place connections (e.g., the host opened a pinhole for this address/port number in a firewall or a NAT using PCP [RFC6887]).

**Comment by markusa** [comment]
@boucadair What is the benefit of such a flag? A non existing Connectivity Check flag cannot be interpreted that the remote host is unreachable. As the initiator of the flow does not know if the remote host is behind a firewall or NAT, it's anyway trial & error. 

And even if the remote host signals that a pinhole exists in middleboxes under control of the remote host, it is not a guarantee that there are other blocking middleboxes.

**Comment by boucadair** [comment]
The value I see in having such a flag is to encourage a remote peer to add a new subflow when needed and not wait for the initiator or for an initiator to systematically add a new path and maintain it while it is not needed for use by the initiator. The presence of the flag is a hint that the incoming connection is likely to succeed. Maintaining and creating subflows will thus be symmetrical for both endpoints of a multipath connection.

**Comment by markusa** [comment]
@boucadair, we had an discussion round among some of the editors and see the use of the **optional** Connectivity Check flag as you propose limited.

But let's clarify first some details to be on the same page.

* Sender of MP_ADDADDR expects its receiver to request a DCCP subflow
* Receiver of MP_ADDADDR is the initiator of a DCCP subflow

1. As long as the receiver of a MP_ADDADDR is not aware that a sender makes use of the flag, its meaning is limited. Only when the receiver knows, e.g., due to earlier reception of a MP_ADDADDR with set flag or pre-knowledge, then the flag can be used to differentiate between set and unset flag. If my understanding holds true, I wonder about the practical relevance.

2. In case the Connectivty Check flag should indicate to the receiver of MP_ADDADDR that a connection request is not desired, than it would be simpler to send no MP_ADDADDR at all. I'm not sure if this was the right interpretation of your last comment.

**Comment by boucadair** [comment]
I fully agree with 2. Many hosts/applications already performs connectivity checks. Some informative guidance, whenever such knowledge is available about the inability to establish incoming connections, to not send MP_ADDADDR is still worth IMO.

A host that send an MP_ADDADDR is expected to gather the external IP address/port so that if it sends such signal to a remote peer, that signal will be useful for the peer (e.g., able to place an incoming subflow).

I think you are right that we don't loose much if we don't include the connectivity check hint if a receiver tries that information to place a new subflow and give it up if a failure is observed. This may not be acceptable for a server that terminates a large number of connections, which will likely rely on the initiator to add more subflows if needed.  The server can advertise its other alternative addresses/ports. 

Thanks for the discussion.

**Comment by markusa** [comment]
> I fully agree with 2. Many hosts/applications already performs connectivity checks. Some informative guidance, whenever such knowledge is available about the inability to establish incoming connections, to not send MP_ADDADDR is still worth IMO.

Thank you @boucadair; I will create a pull request to give some implementation guidelines for MP_ADDADDR.
